include:
  - ../btodo-database/docker-compose.yml

services:
  auth_service:
    container_name: auth_service
    networks:
      - btodo
    build:
      context: ../btodo-auth
      dockerfile: ../btodo-auth/Dockerfile
    command: npm run start:docker
    ports:
      - 50000:50000

  account_service:
    container_name: account_service
    networks:
      - btodo
    build:
      context: ../btodo-account
      dockerfile: ../btodo-account/Dockerfile
    command: npm run start:docker
    ports:
      - 50001:50001

  todo_service:
    container_name: todo_service
    networks:
      - btodo
    build:
      context: ../btodo-todo
      dockerfile: ../btodo-todo/Dockerfile
    command: npm run start:docker
    ports:
      - 50002:50002

  api_gateway:
    container_name: api_gateway
    networks:
      - btodo
    build:
      context: ../btodo-api-gateway
      dockerfile: ../btodo-api-gateway/Dockerfile
    command: npm run start:docker
    ports:
      - 3000:3000

networks:
  btodo:
    name: btodo-network
